### ISSUE TITLE
نکات جهت پیشبرد اهداف

### ISSUE THREAD

**Issue by khanzadimahdi** [KarimQaderi/Zoroaster#4]
سلام. اول اینکه کار جالبی انجام دادین و جای تشکر داره. اما لازم دونستم یه سری نکات رو بهتون بگم تا زحمت هایی که کشیدین هدر نره و سیستمی که نوشتین بیشتر مورد استقبال قرار بگیره

۱- توی فضای نام سیستم بهتره کریم قادری رو حذف کنید و یه کلمه بهتر به عنوان برند استفاده کنید
۲− قالبی که استفاده شده بهتره از یه قالب زیباتر برای ادمین استفاده بشه مثلا استیلسا یا استار ادمین که اوپن سورس هم هستن
۳− توی لنکدین تبلیغ کنید و توی قسمت لینک های لاراول نیوز لینک خودتون رو قرار بدید
۴− ویدیوهای اموزشی که ساختین از نظر فنی اصلا خوب نیست بهتره به جای اینکه متن رو سلکت کنید صحبت کنید و منظور خودتون رو با صحبت کردن منتقل کنید و همزمان که کار رو پیش میبرید توضیحات تکمیلی بدید

موفق باشید.

**Comment by KarimQaderi** [comment]
ممنون از نظرتون
ولی این پنل ادمین بدرد نمی خوره ارزش انتشار دادنشو نداره
چون کد نویسی تمیزی نداره فعلا وقت ندارم وگرنه یه روز وقت شد از اول باید کدنویسویش دوباره بنویسم بیشتر جاهاش نیاز به تغیر داره

برند این پنل ادمین Zoroaster هست

تو ویدیو ساختن زیاد خوب نیستم

**Comment by khanzadimahdi** [comment]
اگه تایم ازاد دارید میتونیم باهم روی ایده شما کار کنیم

موفق باشید

**Comment by KarimQaderi** [comment]
لطفا ایمیلتو چک کن

 khanzadimahdi@gmail.com
